


CREATE TABLE TProcedureError
(
	ErrorUniqueID BIGINT NOT NULL PRIMARY KEY,
	SPID SMALLINT NOT NULL,
	[Procedure] NVARCHAR(128) NOT NULL,
	ErrorTime DATETIMEOFFSET(7) NOT NULL,
	ErrorNumber INT NOT NULL,
	ErrorServerity INT NOT NULL,
	ErrorState INT NOT NULL,
	ErrorProcedure NVARCHAR(128) NOT NULL,
	ErrorLine INT NOT NULL,
	ErrorMessage NVARCHAR(4000) NOT NULL
);